// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Middagsklok.Api.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Middagsklok.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130135217_AddWeeklyPlans")]
    partial class AddWeeklyPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Middagsklok.Api.Domain.Dish.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cuisine");

                    b.Property<string>("Instructions")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cuisine")
                        .HasDatabaseName("ix_dishes_cuisine");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_dishes_name");

                    b.ToTable("dishes", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Api.Domain.Ingredient.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_ingredients_name");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Api.Domain.WeeklyPlan.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_plans_start_date");

                    b.ToTable("weekly_plans", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Api.Domain.Dish.Dish", b =>
                {
                    b.OwnsMany("Middagsklok.Api.Domain.Dish.DishIngredient", "Ingredients", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uuid")
                                .HasColumnName("ingredient_id");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("note");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision")
                                .HasColumnName("quantity");

                            b1.Property<int?>("SortOrder")
                                .HasColumnType("integer")
                                .HasColumnName("sort_order");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("unit");

                            b1.Property<Guid>("dish_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("IngredientId");

                            b1.HasIndex("dish_id", "SortOrder")
                                .HasDatabaseName("ix_dish_ingredients_dish_id_sort_order");

                            b1.ToTable("dish_ingredients", (string)null);

                            b1.HasOne("Middagsklok.Api.Domain.Ingredient.Ingredient", null)
                                .WithMany()
                                .HasForeignKey("IngredientId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_dish_ingredients_ingredient_id");

                            b1.WithOwner()
                                .HasForeignKey("dish_id");
                        });

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Middagsklok.Api.Domain.WeeklyPlan.WeeklyPlan", b =>
                {
                    b.OwnsMany("Middagsklok.Api.Domain.WeeklyPlan.PlannedDay", "Days", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<Guid>("weekly_plan_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("weekly_plan_id", "Date")
                                .IsUnique()
                                .HasDatabaseName("ix_weekly_plan_days_weekly_plan_id_date");

                            b1.ToTable("weekly_plan_days", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("weekly_plan_id");

                            b1.OwnsOne("Middagsklok.Api.Domain.WeeklyPlan.DishSelection", "Selection", b2 =>
                                {
                                    b2.Property<int>("PlannedDayid")
                                        .HasColumnType("integer");

                                    b2.Property<Guid?>("DishId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("dish_id");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("selection_type");

                                    b2.HasKey("PlannedDayid");

                                    b2.HasIndex("DishId");

                                    b2.ToTable("weekly_plan_days");

                                    b2.HasOne("Middagsklok.Api.Domain.Dish.Dish", null)
                                        .WithMany()
                                        .HasForeignKey("DishId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .HasConstraintName("fk_weekly_plan_days_dish_id");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedDayid");
                                });

                            b1.Navigation("Selection")
                                .IsRequired();
                        });

                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
