/* eslint-disable */
// This file is generated by scripts/generate-ingredient-models.mjs. Do not edit by hand.

export type IngredientCategoryValue =
  | "Produce"
  | "Meat"
  | "Poultry"
  | "Seafood"
  | "DairyAndEggs"
  | "PastaAndGrains"
  | "Bakery"
  | "CannedGoods"
  | "FrozenFoods"
  | "Condiments"
  | "SpicesAndHerbs"
  | "Baking"
  | "OilsAndVinegars"
  | "Beverages"
  | "Snacks"
  | "Other";

export type IngredientUnitValue =
  | "G"
  | "Kg"
  | "Ml"
  | "L"
  | "Pcs";
