// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Middagsklok.Database;

#nullable disable

namespace Middagsklok.Migrations
{
    [DbContext(typeof(MiddagsklokDbContext))]
    partial class MiddagsklokDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Middagsklok.Database.Entities.DishEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ActiveMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_minutes");

                    b.Property<int>("FamilyRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("family_rating");

                    b.Property<bool>("HasOptionalMeatVariant")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_optional_meat_variant");

                    b.Property<bool>("IsPescetarian")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pescetarian");

                    b.Property<int>("KidRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kid_rating");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_minutes");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("dish", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.DishHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<Guid>("DishId")
                        .HasColumnType("TEXT")
                        .HasColumnName("dish_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int?>("RatingOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating_override");

                    b.HasKey("Id");

                    b.HasIndex("DishId", "Date")
                        .HasDatabaseName("ix_dish_history_dish_date");

                    b.ToTable("dish_history", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.DishIngredientEntity", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("TEXT")
                        .HasColumnName("dish_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<bool>("Optional")
                        .HasColumnType("INTEGER")
                        .HasColumnName("optional");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("dish_ingredient", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ingredient", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.WeeklyPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("WeekStartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("week_start_date");

                    b.HasKey("Id");

                    b.HasIndex("WeekStartDate")
                        .IsUnique();

                    b.ToTable("weekly_plan", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.WeeklyPlanItemEntity", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT")
                        .HasColumnName("plan_id");

                    b.Property<int>("DayIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_index");

                    b.Property<Guid>("DishId")
                        .HasColumnType("TEXT")
                        .HasColumnName("dish_id");

                    b.HasKey("PlanId", "DayIndex");

                    b.HasIndex("DishId");

                    b.ToTable("weekly_plan_item", (string)null);
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.DishHistoryEntity", b =>
                {
                    b.HasOne("Middagsklok.Database.Entities.DishEntity", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.DishIngredientEntity", b =>
                {
                    b.HasOne("Middagsklok.Database.Entities.DishEntity", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Middagsklok.Database.Entities.IngredientEntity", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.WeeklyPlanItemEntity", b =>
                {
                    b.HasOne("Middagsklok.Database.Entities.DishEntity", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Middagsklok.Database.Entities.WeeklyPlanEntity", "Plan")
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.DishEntity", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.IngredientEntity", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("Middagsklok.Database.Entities.WeeklyPlanEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
